---
title: "FunGuilds"
output: html_document
date: "2023-06-07"
---
```{r}
library(ape)
library(vegan)
library(dplyr)
library(phyloseq)
library(ggplot2)
```


######ZONE#####
```{r}
#Load mapping file into R
meta <- read.table("DroughtITS.mapping_file.fix.txt",header=TRUE,row.names=1,sep="\t",stringsAsFactors=FALSE)
sampleData <- sample_data(meta)
```

```{r}
#Load reformatted FUNGuild data into R
FG <- read.table("DroughtITS.guilds.fix1.txt",header=T,sep="\t",row.names=1)
```

```{r}
#Select only the column that we need
FGotus <- select(FG, -(Taxonomy:citationSource))
FGotumat <- as(as.matrix(FGotus), "matrix")
FGOTU <- otu_table(FGotumat, taxa_are_rows = TRUE)
FGtaxmat <- select(FG, confidenceRanking, trophicMode, guild, growthForm)
FGtaxmat <- as(as.matrix(FGtaxmat),"matrix")
FGTAX = tax_table(FGtaxmat)
```

```{r}
#Creating phyloseq object
physeq = phyloseq(FGOTU,FGTAX,sampleData)
physeq.prune = prune_taxa(taxa_sums(physeq) > 1, physeq)
physeq.prune.nopossible = subset_taxa(physeq.prune, confidenceRanking="Highly Possible")
physeq.prune.nopossible = subset_taxa(physeq.prune.nopossible, confidenceRanking!="-")
```

```{r}
#Create color palette
cbbPalette <- c("#009E73", "#E69F00", "#56B4E9", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "midnightblue", "lightgreen","saddlebrown", "brown", "aquamarine4","lavenderblush2","snow3", "darkblue", "darkgoldenrod1", "darkseagreen", "darkorchid", "darkolivegreen1", "black","lightskyblue", "darkgreen", "deeppink", "khaki2", "firebrick", "brown1", "darkorange1", "cyan1", "royalblue4", "darksalmon", "darkblue","royalblue4", "dodgerblue3", "steelblue1", "lightskyblue", "darkseagreen", "darkgoldenrod1", "darkseagreen", "darkorchid", "darkolivegreen1", "brown1", "darkorange1", "cyan1", "darkgrey")
```

```{r}
sampleData(physeq.prune.nopossible)$zone = factor(sampleData(physeq.prune.nopossible)$zone, levels = c('one', 'two', 'three', 'four', 'five', 'six', 'seven' ,'eight'))
```


```{r}
#Create a plot
FUNGuildcom = ggplot(data = psmelt(physeq.prune.nopossible), mapping = aes_string(x = "zone" ,y = "Abundance", fill = "trophicMode" )) + geom_bar(stat="identity", position="fill") + ggtitle("Fungal Trophic Mode Composition (Geolegical zone)") + theme_minimal() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + scale_fill_manual(values = cbbPalette) 
FUNGuildcom
```


```{r}
#Save a plot to PDF file
#pdf("./Fungal Trophic Mode Composition zone.pdf", width = 8, height = 5)
#FUNGuildcom
#dev.off()
#pdf  
```

```{r}
png("./Fungal_TrophicMode_zone.png", units="in", width = 12, height = 7.5, res = 600 )
FUNGuildcom + theme(legend.position="right") + theme(axis.text.x = element_text(angle = 45, hjust = 1))
dev.off()
```


######PLANT#####
```{r}
#Load mapping file into R
meta <- read.table("DroughtITS.mapping_file.fix.txt",header=TRUE,row.names=1,sep="\t",stringsAsFactors=FALSE)
sampleData <- sample_data(meta)
```

```{r}
#Load reformatted FUNGuild data into R
FG <- read.table("DroughtITS.guilds.fix1.txt",header=T,sep="\t",row.names=1)
```

```{r}
#Select only the column that we need
FGotus <- select(FG, -(Taxonomy:citationSource))
FGotumat <- as(as.matrix(FGotus), "matrix")
FGOTU <- otu_table(FGotumat, taxa_are_rows = TRUE)
FGtaxmat <- select(FG, confidenceRanking, trophicMode, guild, growthForm)
FGtaxmat <- as(as.matrix(FGtaxmat),"matrix")
FGTAX = tax_table(FGtaxmat)
```

```{r}
#Creating phyloseq object
physeq = phyloseq(FGOTU,FGTAX,sampleData)
physeq.prune = prune_taxa(taxa_sums(physeq) > 1, physeq)
physeq.prune.nopossible = subset_taxa(physeq.prune, confidenceRanking="Highly Possible")
physeq.prune.nopossible = subset_taxa(physeq.prune.nopossible, confidenceRanking!="-")
```

```{r}
#Create color palette
cbbPalette <- c("#009E73", "#E69F00", "#56B4E9", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "midnightblue", "lightgreen","saddlebrown", "brown", "aquamarine4","lavenderblush2","snow3", "darkblue", "darkgoldenrod1", "darkseagreen", "darkorchid", "darkolivegreen1", "black","lightskyblue", "darkgreen", "deeppink", "khaki2", "firebrick", "brown1", "darkorange1", "cyan1", "royalblue4", "darksalmon", "darkblue","royalblue4", "dodgerblue3", "steelblue1", "lightskyblue", "darkseagreen", "darkgoldenrod1", "darkseagreen", "darkorchid", "darkolivegreen1", "brown1", "darkorange1", "cyan1", "darkgrey")
```


```{r}
#Create a plot
FUNGuildcom = ggplot(data = psmelt(physeq.prune.nopossible), mapping = aes_string(x = "plant" ,y = "Abundance", fill = "trophicMode" )) + geom_bar(stat="identity", position="fill") + ggtitle("Fungal Trophic Mode Composition (Plant)") + theme_minimal() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + scale_fill_manual(values = cbbPalette) 
FUNGuildcom
```


```{r}
png("./Fungal_TrophicMode_plant.png", units="in", width = 12, height = 7.5, res = 600 )
FUNGuildcom + theme(legend.position="right") + theme(axis.text.x = element_text(angle = 45, hjust = 1))
dev.off()
```
